name: 'Build Docs'

inputs:
  asdf-system:
    description: 'ASDF system to build system for'
    required: true
  qlfile-template:
    description: "Djula template for qlfile. All environment variables are available in it's context"
    required: false
  ngrok-auth-token:
    description: "A token to debug processes."
    required: false

runs:
  using: composite
  steps:
    - name: Install Documentation Builder
      shell: bash
      run: |
        echo ::group::Install Documentation Builder

        echo 'github docs-builder 40ants/docs-builder' >> qlfile
        echo 'github ngrok 40ants/ngrok' >> qlfile
        
        qlot update

        qlot exec ros install docs-builder
        qlot exec ros install ngrok
        echo ::endgroup::
    - name: Build Docs
      id: build-docs
      shell: bash
      run: |
        set -Eeuo pipefail
        echo ::group::Build Docs

        build-docs ${{ inputs.asdf-system }} output.dir

        echo ::endgroup::

    - name: Upload Docs
      shell: bash
      run: |
        set -Eeuo pipefail
        echo ::group::Upload Docs

        ${{ github.action_path }}/upload.ros "$(cat output.dir)"

        echo ::endgroup::
      env:
        GITHUB_TOKEN: ${{ github.token }}
        NGROK_AUTH_TOKEN: ${{ inputs.ngrok-auth-token }}
