{
  "name": "CI",
  "on": {
    "push": {
      "branches": ["workflow-generator"]
    }
  },
  "jobs": {
    "build": {
      "runs-on": "ubuntu-latest",
      "steps": [
         {
           "name": "Just a test",
           "run": "echo Hello"
         }
      ]
    }
  }
}
