{
  "name": "CI",
  "on": {
    "push": {
      "branches": [
        "master"
      ]
    },
    "pull_request": null,
    "schedule": [
      {
        "cron": "0 10 * * 1"
      }
    ]
  },
  "jobs": {
    "run-tests": {
      "strategy": {
        "fail-fast": false,
        "matrix": {
          "os": [
            "ubuntu-latest",
            "macos-latest"
          ],
          "exclude": [
            {
              "os": "macos-latest",
              "lisp": "allegro"
            },
            {
              "os": "macos-latest",
              "quicklisp": "ultralisp",
              "lisp": "clisp"
            },
            {
              "os": "macos-latest",
              "lisp": "cmucl"
            },
            {
              "os": "ubuntu-latest",
              "lisp": "clisp"
            },
            {
              "os": "ubuntu-latest",
              "lisp": "allegro"
            },
            {
              "os": "ubuntu-latest",
              "lisp": "cmucl"
            },
            {
              "os": "macos-latest",
              "lisp": "ccl-bin"
            }
          ],
          "quicklisp": [
            "quicklisp",
            "ultralisp"
          ],
          "lisp": [
            "sbcl-bin",
            "ccl-bin",
            "allegro",
            "ecl",
            "allegro",
            "clisp",
            "cmucl"
          ]
        }
      },
      "runs-on": "${{ matrix.os }}",
      "env": {
        "OS": "${{ matrix.os }}",
        "QUICKLISP_DIST": "${{ matrix.quicklisp }}",
        "LISP": "${{ matrix.lisp }}"
      },
      "steps": [
        {
          "name": "Checkout Code",
          "uses": "actions/checkout@v4"
        },
        {
          "name": "Setup Common Lisp Environment",
          "uses": "40ants/setup-lisp@v4",
          "with": {
            "asdf-system": "cl-info-ci",
            "qlfile-template": "{% ifequal quicklisp_dist \"ultralisp\" %}\ndist ultralisp http://dist.ultralisp.org\n{% endifequal %}",
            "cache": "true"
          }
        },
        {
          "name": "Run Tests",
          "uses": "40ants/run-tests@v2",
          "with": {
            "asdf-system": "cl-info-ci",
            "coveralls-token": "\n${{ matrix.lisp == 'sbcl-bin' &&\n    matrix.os == 'ubuntu-latest' &&\n    matrix.quicklisp == 'ultralisp' &&\n    secrets.github_token }}"
          }
        },
        {
          "name": "Run Command Line Version",
          "run": "echo ::group::Help Argument\nqlot exec cl-info --help\necho ::endgroup::\necho ::group::Version Argument\nqlot exec cl-info --version\necho ::endgroup::\necho ::group::Lisp Systems Info\nqlot exec cl-info cl-info defmain\necho ::endgroup::\n",
          "shell": "bash"
        }
      ]
    }
  }
}