{ "jobs": { "tests": { "steps": [{ "uses": "actions/checkout@v1" }, { "run": "sudo mkdir -p /usr/local/etc/roswell
sudo chown \"${USER}\" /usr/local/etc/roswell
# Here the ros binary will be restored:
sudo chown \"${USER}\" /usr/local/bin
", "name": "Grant All Perms to Make Cache Restoring Possible" }, { "run": "echo \"::set-output name=value::$(date -u \"+%Y-%m\")\"
", "id": "current-month", "name": "Get Current Month" }, { "with": { "key": "${{ steps.current-month.outputs.value }}-${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.quicklisp-dist }}-${{ matrix.lisp }}-${{ hashFiles('qlfile.lock') }}", "path": "qlfile
qlfile.lock
/usr/local/bin/ros
~/.cache/common-lisp/
~/.roswell
/usr/local/etc/roswell
.qlot
" }, "env": { "cache-name": "cache-roswell" }, "uses": "actions/cache@v2", "id": "cache", "name": "Cache Roswell Setup" }, { "if": "steps.cache.outputs.cache-hit == 'true'", "run": "echo $HOME/.roswell/bin >> $GITHUB_PATH
echo .qlot/bin >> $GITHUB_PATH
", "name": "Restore Path To Cached Files" }, { "if": "steps.cache.outputs.cache-hit != 'true'", "with": { "qlfile-template": "{% ifequal quicklisp_dist \"ultralisp\" %}
dist ultralisp http://dist.ultralisp.org
{% endifequal %}

github mgl-pax svetlyak40wt/mgl-pax :branch mgl-pax-minimal
", "asdf-system": "cl-info" }, "uses": "40ants/setup-lisp@v1" }, { "run": "ros config", "name": "Check Roswell setup" }, { "with": { "coveralls-token": "${{ matrix.lisp == 'sbcl-bin' &&
    matrix.os == 'ubuntu-latest' &&
    matrix.quicklisp-dist == 'ultralisp' &&
    secrets.github_token }}
", "asdf-system": "cl-info" }, "uses": "40ants/run-tests@v2" }, { "run": "
echo ::group::Help Argument
qlot exec cl-info --help
echo ::endgroup::

echo ::group::Version Argument
qlot exec cl-info --version
echo ::endgroup::

echo ::group::Lisp Systems Info
qlot exec cl-info cl-info defmain
echo ::endgroup::
", "name": "Run Command Line Version" }], "env": { "QUICKLISP_DIST": "${{ matrix.quicklisp-dist }}", "OS": "${{ matrix.os }}", "LISP": "${{ matrix.lisp }}" }, "strategy": { "matrix": { "exclude": [{ "lisp": "allegro", "os": "macos-latest" }, { "quicklisp-dist": "ultralisp", "lisp": "clisp", "os": "macos-latest" }, { "lisp": "cmucl", "os": "macos-latest" }, { "lisp": "clisp", "os": "ubuntu-latest" }, { "lisp": "allegro", "os": "ubuntu-latest" }, { "lisp": "cmucl", "os": "ubuntu-latest" }], "lisp": ["sbcl-bin", "ccl-bin", "ecl", "abcl", "allegro", "clisp", "cmucl"], "quicklisp-dist": ["quicklisp", "ultralisp"], "os": ["ubuntu-latest", "macos-latest"] }, "fail-fast": false }, "runs-on": "${{ matrix.os }}" }, "linter": { "steps": [{ "uses": "actions/checkout@v1" }, { "with": { "asdf-system": "cl-info" }, "uses": "40ants/setup-lisp@v1" }, { "run": "qlot exec ros install cxxxr/sblint
", "name": "Install SBLint" }, { "run": "qlot exec sblint cl-info.asd cl-info-test.asd
", "name": "Run Linter" }], "env": { "LISP": "sbcl-bin" }, "runs-on": "ubuntu-latest" } }, "on": { "schedule": [{ "cron": "0 10 * * 1" }], "pull_request": "", "push": { "branches": ["main", "master"] } }, "name": "CI" }